"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CalendarDays,Check,ChevronDown,Clock3,ExternalLink,MapPin,Menu,MessageCircle,Phone,ShieldCheck,Star,Stethoscope,X} from 'lucide-react';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import {buildWhatsAppUrl,clinicPhone} from '../lib/contact';gsap.registerPlugin(ScrollTrigger);

const doctorImage='https://bigohealth-images.s3.amazonaws.com/Doctor_bettiah/dr-mughda-mohan-bettiah.jpeg';
const clinicHero='https://lh3.googleusercontent.com/S8fBKBvkDX1OGC3aD4ZYFcntq1LHQK1jBhrNH0VWKRhXrSxxsmBxioFQH10vLUQ8ucptSl6u2Pid41VbNq6F7UAIse9aKZ8SKmDMiwlI=w1600-rw';
const gallery=['https://img.magicpin.com/9713313_store_images_0.webp','https://img.magicpin.com/9713313_store_images_1.webp','https://img.magicpin.com/9713313_store_images_2.webp'];
const brandImage=doctorImage;
const wa=(m:string)=>buildWhatsAppUrl(m);
const concerns=[['Acne & acne scars','Persistent acne, breakouts and post-acne concerns.'],['Hair & scalp','Hair fall and common scalp concerns assessed clinically.'],['Pigmentation','Melasma, dark spots and uneven pigmentation.'],['Psoriasis & eczema','Recurring and inflammatory skin conditions.'],['Skin allergies','Rashes, itching and suspected allergic conditions.'],['Moles & lesions','Clinical assessment and selected dermatological procedures.']];
const procedures=['Chemical peels','PRP & mesotherapy','Laser hair removal','Q-switched Nd:YAG laser','Diode & CO₂ laser','Radio / electro cautery','Mole & cyst procedures','Scar revision','HydraFacial'];
const reviews=[['Abhishek Kumar','I struggled with a persistent skin problem for over a year. After following Dr. Mugdha’s treatment plan, I saw a major improvement.'],['Akshat Raj Gupta','She listens carefully and explains treatment clearly. Her professional and empathetic approach makes the consultation comfortable.'],['Dr. Afreen Fiza','She has very good clinical knowledge, builds rapport and carefully examines patients before treatment.'],['Arya Singh','I consulted her for acne and hair fall and was satisfied with the treatment. She has a very good approach towards her patients.']];

export default function Home(){
 const [menu,setMenu]=useState(false),[booking,setBooking]=useState(false);const root=useRef<HTMLElement>(null);
 useEffect(()=>{const c=gsap.context(()=>{gsap.from('.hero-copy>*',{y:30,opacity:0,duration:.8,stagger:.08,ease:'power3.out'});gsap.from('.hero-portrait',{scale:1.04,opacity:0,duration:1,ease:'power3.out'});gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(e=>gsap.from(e,{y:38,opacity:0,duration:.8,scrollTrigger:{trigger:e,start:'top 82%'}}));},root);return()=>c.revert()},[]);
 const jsonLd={'@context':'https://schema.org','@type':'Physician',name:'Dr. Mugdha Mohan',medicalSpecialty:'Dermatology',description:'MBBS, MD (Dermatology, Venereology & Leprosy) dermatologist practising in Bettiah, Bihar.',url:'https://www.drmugdhamohan.in',telephone:'+91 92170 02598',address:{'@type':'PostalAddress',streetAddress:'West of Kotwali Chowk, Hospital Road, Kali Bagh Colony',addressLocality:'Bettiah',addressRegion:'Bihar',postalCode:'845438',addressCountry:'IN'},geo:{'@type':'GeoCoordinates',latitude:26.7976052,longitude:84.4953882},aggregateRating:{'@type':'AggregateRating',ratingValue:'4.8',reviewCount:'176'}};
 return <main ref={root} id="top"><div className="topline"><span>Dermatology · Bettiah, Bihar</span><span>Appointment by enquiry · {clinicPhone}</span></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <header className="nav"><a className="brand" href="#top" aria-label="Dr. Mugdha Mohan home"><span className="brand-avatar"><img src={brandImage} alt="" /></span><span>Dr. Mugdha Mohan</span></a><nav className="desktop" aria-label="Primary"><a href="#about">About</a><a href="#care">Concerns</a><a href="#procedures">Procedures</a><a href="#research">Research</a><a href="#reviews">Patient voices</a><a href="#clinic">Clinic</a></nav><div className="nav-right"><a className="nav-wa" href={wa('Hello, I would like to enquire about a dermatology consultation.')} target="_blank"><MessageCircle size={15}/> WhatsApp</a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="mobile">{['about','care','procedures','research','reviews','clinic'].map(x=><a key={x} href={'#'+x} onClick={()=>setMenu(false)}>{x}</a>)}</nav>}</header>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><i/> Skin · Hair · Scalp</div><div className="hero-kicker">A calmer way to approach dermatology.</div><h1>Understand the skin.<em>Then treat it.</em></h1><p>Personalised dermatology care in Bettiah, built around careful clinical assessment, clear explanations and treatment plans that make sense for the person in front of the doctor.</p><div className="actions"><button className="btn dark" onClick={()=>setBooking(true)}>Request a consultation <ArrowRight size={16}/></button><a className="link" href="#care">Explore care <ArrowRight size={15}/></a></div><div className="proof"><div><b>4.8</b><small><Star size={12} fill="currentColor"/> 176 public reviews</small></div><span/><div><b>MD (DVL)</b><small>Dermatology · Venereology · Leprosy</small></div></div><div className="hero-note"><ShieldCheck size={14}/> Evidence-led thinking. Human consultation. Practical next steps.</div></div><div className="hero-art"><div className="portrait"><img className="hero-portrait" src={doctorImage} alt="Dr. Mugdha Mohan, dermatologist in Bettiah"/><div className="caption"><strong>Dr. Mugdha Mohan</strong><small>MBBS · MD (DVL)</small></div></div><div className="floating-card"><ShieldCheck size={16}/><span>Evidence-led care.<b> Human consultation.</b></span></div></div></section>
  <div className="ribbon">ACNE <i>✦</i> HAIR LOSS <i>✦</i> PIGMENTATION <i>✦</i> PSORIASIS <i>✦</i> ECZEMA <i>✦</i> SKIN ALLERGIES <i>✦</i> LASER DERMATOLOGY</div>
  <div className="signal-band"><div><span>The visit, reimagined</span><p>Less guesswork. More context. A clearer conversation about what comes next.</p></div></div><section className="section intro" id="about" data-reveal><div className="kicker">A dermatologist you can talk to</div><div className="two"><h2>Clinical depth, explained in a way that <em>makes sense.</em></h2><div><p>Good dermatology starts with listening, examining carefully and choosing an appropriate plan for the condition, skin type and goals of the patient.</p><p>Dr. Mugdha Mohan is an MBBS and MD (Dermatology, Venereology & Leprosy) dermatologist practising in Bettiah, with experience in outpatient dermatology and dermatological procedures.</p><a className="link" href="#clinic">Find the clinic <ArrowRight size={15}/></a></div></div></section>
  <section className="section care" id="care" data-reveal><div className="section-topline"><span>02 · Start with the concern</span><span>Educational information · not a diagnosis</span></div><div className="head"><div><div className="kicker">What can we help with?</div><h2>Start with the concern.<br/><em>We’ll start with the why.</em></h2></div><p>Common concerns need different approaches. This section is educational and does not replace diagnosis.</p></div><div className="grid">{concerns.map(([t,d],i)=><article className="card" key={t}><small>0{i+1}</small><h3>{t}</h3><p>{d}</p><div className="card-actions"><a href={wa('Hello, I would like to enquire about '+t+'.')} target="_blank" rel="noreferrer">Enquire <ArrowRight size={14}/></a></div></article>)}</div></section>
  <section className="section quote" data-reveal><span/> <p>“The goal is not to make every skin look the same. It is to understand <em>your</em> skin and treat it appropriately.”</p><small>— Dr. Mugdha Mohan</small></section>
  <section className="section procedure" id="procedures" data-reveal><div className="wide-img"><img src={clinicHero} alt="Skin Care Centre in Bettiah" loading="lazy"/></div><div><div className="kicker">Dermatology procedures</div><h2>When a procedure is appropriate, <em>precision matters.</em></h2><p>Selected procedures are offered based on clinical assessment and suitability. A consultation comes before treatment planning.</p><div className="procedure-list">{procedures.map(p=><span key={p}><Check size={14}/>{p}</span>)}</div><button className="btn outline" onClick={()=>setBooking(true)}>Ask about a procedure <ArrowRight size={15}/></button></div></section>
  <section className="section research" id="research" data-reveal><div className="section-topline"><span>04 · Clinical & academic work</span><span>2024</span></div><div className="research-main"><div className="research-meta"><span>Clinical & academic work</span><span>2024</span></div><h2>Dermatology is a field that keeps <em>learning.</em></h2><p>Dr. Mugdha Mohan has been listed as a Senior Resident in Dermatology, Venereology & Leprosy at Government Medical College & Hospital, Bettiah, and as corresponding author on published clinical research.</p><a className="link" href="https://impactfactor.org/PDF/IJPCR/16/IJPCR%2CVol16%2CIssue12%2CArticle374.pdf" target="_blank" rel="noreferrer">View published research <ExternalLink size={14}/></a></div><aside><b>01</b><p>Clinical-epidemiological research on childhood leprosy in Bettiah.</p><small>International Journal of Pharmaceutical and Clinical Research · 2024</small></aside></section>
  <section className="section reviews" id="reviews" data-reveal><div className="section-topline"><span>05 · Patient voices</span><span>Public review excerpts</span></div><div className="kicker">Patient voices</div><div className="review-head"><h2>Care is also about<br/><em>how you feel heard.</em></h2><div className="score"><b>4.8</b><span>★★★★★</span><small>176 public reviews</small></div></div><div className="review-grid">{reviews.map(([n,t])=><article key={n}><span>★★★★★</span><p>“{t}”</p><b>{n}</b></article>)}</div></section>
  <section className="section clinic" id="clinic" data-reveal><div className="section-topline"><span>06 · Visit the clinic</span><span>Skin Care Centre · Bettiah</span></div><div><div className="kicker">Visit the clinic</div><h2>Skin Care Centre<br/><em>Dr. Mugdha Mohan</em></h2><div className="details"><div><MapPin size={17}/><span>West of Kotwali Chowk, Hospital Road,<br/>Kali Bagh Colony, Bettiah, Bihar 845438</span></div><div><Clock3 size={17}/><span>Public listings show daytime hours.<br/>Please confirm availability before visiting.</span></div><div><Phone size={17}/><span>+91 92170 02598</span></div></div><div className="actions"><button className="btn dark" onClick={()=>setBooking(true)}>Request appointment <CalendarDays size={15}/></button><a className="btn soft" href="https://www.google.com/maps?q=26.7976052,84.4953882" target="_blank" rel="noreferrer">Directions <MapPin size={15}/></a></div></div><div className="gallery"><div><img src={gallery[0]} alt="Skin Care Centre" loading="lazy"/></div><div><img src={gallery[1]} alt="Skin Care Centre" loading="lazy"/><img src={gallery[2]} alt="Skin Care Centre" loading="lazy"/></div></div></section>
  <section className="final" data-reveal><div className="section"><div className="kicker">Your skin has a story.</div><h2>Let’s understand it<br/><em>before we treat it.</em></h2><button className="btn light" onClick={()=>setBooking(true)}>Request a consultation <ArrowRight size={16}/></button></div></section>
  <div className="mobile-bottom-cta"><a className="mobile-home" href="#top" aria-label="Home"><span className="brand-avatar mini"><img src={brandImage} alt="" /></span></a><button onClick={()=>setBooking(true)}><CalendarDays size={15}/> Request appointment</button><a href={wa('Hello, I would like to enquire about an appointment.')} target="_blank" rel="noreferrer" aria-label="WhatsApp clinic"><MessageCircle size={16}/></a></div><footer><div className="footer-top"><div><a className="brand" href="#top"><span className="brand-avatar"><img src={brandImage} alt="" /></span><span>Dr. Mugdha Mohan</span></a><p>MBBS · MD (Dermatology, Venereology & Leprosy)<br/>Dermatologist · Bettiah</p></div><div className="footer-links"><a href="#about">About</a><a href="#care">Concerns</a><a href="#procedures">Procedures</a><a href="#reviews">Patient voices</a><a href="#clinic">Clinic</a></div><a className="footer-wa" href={wa('Hello, I would like to book a dermatology consultation.')} target="_blank"><MessageCircle size={15}/> WhatsApp the clinic</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dr. Mugdha Mohan</span><span>Educational information only · consultation required for diagnosis.</span></div></footer>
  {booking&&<BookingModal close={()=>setBooking(false)}/>}<a className="floating" href={wa('Hello, I would like to enquire about an appointment.')} target="_blank" rel="noreferrer" aria-label="WhatsApp clinic"><MessageCircle/></a>
 </main>
}

function BookingModal({close}:{close:()=>void}){const [state,setState]=useState('idle');const [f,setF]=useState({name:'',phone:'',concern:'',date:''});useEffect(()=>{const onKey=(e:KeyboardEvent)=>e.key==='Escape'&&close();window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[close]);async function submit(e:React.FormEvent){e.preventDefault();setState('loading');try{const r=await fetch('/api/appointment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:f.name,phone:f.phone,concern:f.concern,preferredDate:f.date})});if(!r.ok)throw 0;const d=await r.json();window.location.href=d.whatsappUrl;setState('done')}catch{setState('error')}}return <div className="backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={close}><X/></button>{state==='done'?<div className="success"><div className="success-mark"><Check/></div><h2>Enquiry prepared.</h2><p>Your WhatsApp window should open with the clinic details. The clinic team can confirm availability.</p><button className="btn dark" onClick={close}>Done</button></div>:<><div className="kicker">Appointment enquiry</div><h2>Tell the clinic what you need.</h2><p className="modal-note">This is an enquiry form, not a diagnostic service.</p><form onSubmit={submit}><label>Name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Phone<input required pattern="[0-9 +()\\-]{10,16}" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Concern<select required value={f.concern} onChange={e=>setF({...f,concern:e.target.value})}><option value="">Select a concern</option>{concerns.map(([x])=><option key={x}>{x}</option>)}<option>Other</option></select></label><label>Preferred date<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label>{state==='error'&&<p className="error">Please use WhatsApp directly if the enquiry form is unavailable.</p>}<button className="btn dark submit" disabled={state==='loading'}>{state==='loading'?'Preparing…':'Continue to WhatsApp'} <ArrowRight size={15}/></button></form></>}</div></div>}
